apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: example-voting-app
build:
  tagPolicy:
    envTemplate:
      template: "{{.AMBIENTE}}-{{.VERSION}}"
  local:
    push: true
  artifacts:
  - image: docker.io/cbrunosps/examplevotingapp_result
    context: result
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - kubernetes-specifications/*
