apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-metrics
  namespace: default
stringData:
  username: '514446'
  password: 'eyJrIjoiNDRhZGY2YzE3YzQ0ODE5NmI1YmY2ZWYxMDE0MGMxOGMyYzUzZGVmOSIsIm4iOiJla3MiLCJpZCI6Njg0NjUwfQ=='
