apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-logs
  namespace: default
stringData:
  username: '256193'
  password: 'eyJrIjoiZTJmNDAwYjNjMTNkMTdkODNiNmI0M2NjZTNjMzA3YmYwYjA3ZGRhNyIsIm4iOiJsb2tpX2VrcyIsImlkIjo2ODQ2NTB9'
