apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"          

spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: docker.io/cbrunosps/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result

