apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  annotations:
    prometheus.io/port: "9090"          

spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: docker.io/cbrunosps/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
      - image: docker.io/bitnami/prometheus
        name: prometheus
        ports:
          - containerPort: 9090
            name: prometheus
