name: 0 Deploy Terraform 🌎

concurrency: production

on:
  workflow_dispatch:
    inputs:
      terraform:
        description: 'Deploy Terraform OCI? ☁️'
        default: false
        required: true
        type: boolean
      terraform_dr:
        description: 'Deploy Terraform AWS? ☁️'
        default: false
        required: true
        type: boolean
      monitoring:
        description: 'Deploy Prometheus? 🔎'
        default: false
        required: true
        type: boolean
defaults:
  run:
    working-directory: "infra"

env:
  KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

permissions:
  id-token: write
  contents: read

jobs:

### Terraform plan
  Infra_plan:
    if: ${{ inputs.terraform == true }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: hashicorp/setup-terraform@v2    

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      working-directory: "infra/oci"

### Terraform DR
  Infra_plan_DR:
    if: ${{ inputs.terraform_dr == true }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: hashicorp/setup-terraform@v2 
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{secrets.DEV_AWS_ACCOUNT_ID}}:role/github-role-skaffold-demo
        role-session-name: github-role-skaffold-demo
        aws-region: us-west-2
        
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      working-directory: "infra/aws"

### Terraform apply
  Infra_deploy:
    needs: Infra_plan
    runs-on: ubuntu-22.04
    environment: 'infra'
    steps:
    - name: Deploying prometheus
      if: ${{ inputs.prometheus == true }}
      run: |
        terraform apply -auto-approve
      working-directory: "infra/oci"

### Terraform apply DR
  Infra_deploy_DR:
    needs: Infra_plan_DR
    runs-on: ubuntu-22.04
    environment: 'infra'
    steps:
    - name: Deploying prometheus
      if: ${{ inputs.prometheus == true }}
      run: |
        terraform apply -auto-approve
      working-directory: "infra/aws"
    
### Monitoring DR
  Monitoring_deploy_DR:
    if: ${{ inputs.monitoring == true }}
    needs: Infra_deploy_DR   
    uses: cbrunosps/skaffold_k8s_deploy/.github/workflows/reusable_monitoring.yml@main
    with:
    secrets: inherit